### ISSUE TITLE
sidebar icons

### ISSUE THREAD

**Issue by Halil777** [Halil777/Business#9]
Need to change sidebar icons

**Comment by Halil777** [comment]
Iskender agan ozunin saylap goy diyen iconlary  oz gownune yaramady , son ucin basga icon gymaly , olaram ozum saylap ugratjak diydi , poka sona garasyp dur Sidebar iconlar

**Comment by saggeldi** [comment]
Belki lottie files saylap goyarsyn icon-laryn yerine, Iskender-e ugradyp gor shulardan saylay bolmasa diy:

https://lottiefiles.com/free-animation/home-icon-loading-zeZXGVKNVY?from=search

**Comment by Halil777** [comment]
basda mui iconlar goyuldy , son ant design iconlar goyuldy , son UI-da cyzylan iconlar goyuldy , son react-iconslar goyuldy , onda-da bolmanson lottie files iconlaram gorkezdim olaram bolmady , son ozi sulary goy diyip ugratdy indi olaram bolanak , ozi anyk belli bir zady goy diymese indi basga bilemak

**Comment by saggeldi** [comment]
Bolya gyssap caltyrak dynda, basga ish yokmy on ikonkasyna garashmakdan

**Comment by Halil777** [comment]
ozune yazyp goydum atwet berenak entek
